### ISSUE TITLE
SporeStack refund address

### ISSUE THREAD

**Issue by ghost** [nikosch86/investiGator#2]
Hi Niko,

This is really cool! Had no idea you had integrated SporeStack here.

Just wanted to let you know about the refund address. It isn't in use and will probably be removed entirely. I added it hoping to add support there but it's ended up being too complicated and will probably never happen (at least in that form).

Thought I should note that in case anyone was expecting that to work somehow. The address isn't even saved anywhere.

-Teran

**Comment by nikosch86** [comment]
Thank you @teran-mckinney

**Comment by ghost** [comment]
Awesome, thank you!
